classDiagram
   class User{
    -username: string-id
    -hashPassword: string
    -email: string
    -name: string
   }
   class LotteryResult{
    -id: string-id
    -date: date
    -source: string
   }
   class LotteryNumber{
    -prize: string
    -number: string
   }

   class 